# Generated by Django 4.1.5 on 2023-01-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_user_admission_number_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='roll',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
