# Generated by Django 4.1.5 on 2023-01-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_marklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marklist',
            name='subject',
        ),
        migrations.AddField(
            model_name='marklist',
            name='grade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marklist',
            name='percentage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marklist',
            name='s1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marklist',
            name='s10',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marklist',
            name='s2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marklist',
            name='s3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marklist',
            name='s4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marklist',
            name='s5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marklist',
            name='s6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marklist',
            name='s7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marklist',
            name='s8',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marklist',
            name='s9',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
