# Generated by Django 4.1.5 on 2023-01-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_mark_list_grade_remove_mark_list_s10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark_list',
            name='grade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
