# Generated by Django 4.1.5 on 2023-01-24 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_mark_list_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark_list',
            name='user_id',
        ),
    ]
