# Generated by Django 4.1.5 on 2023-01-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_mark_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark_list',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
