# Generated by Django 4.1.5 on 2023-01-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_mark_list_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='standard',
            field=models.CharField(choices=[('10A', '10A'), ('10B', '10B'), ('9A', '9A'), ('9B', '9B'), ('8A', '8A'), ('8B', '8B')], max_length=10, null=True),
        ),
    ]
