# Generated by Django 4.1.5 on 2023-01-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_user_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Teaching_subjects',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
