# Generated by Django 4.1.5 on 2023-02-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_remove_user_teaching_subjects_user_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
